import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextThemeProvider from '@/provider/theme-provider'
import NextAuthProvider from '@/provider/next-auth-provider'
import GlobalState from '@/context'
import Header from '@/components/header'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark:bg-black'>
        <NextThemeProvider>
          <NextAuthProvider>
            <GlobalState>
              <Header></Header>
              {children}
            </GlobalState>
          </NextAuthProvider>
        </NextThemeProvider>
      </body>
    </html>
  )
}
